version: '3.7'
services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stunning-journey
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    container_name: api
    env_file: '.env'
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      bash -c "
      sleep 5
      && npm install
      && prisma generate
      && prisma migrate dev --name init
      && npm run start:dev"
    volumes:
      - ./:/usr/src/stunning-journey-api
      - /usr/src/stunning-journey-api/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DOCKER: 'true'
volumes:
  pgdata:
